name: rabbit_fbi
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - asn1crypto=0.24.0
  - bokeh=1.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cartopy=0.17.0
  - certifi=2019.3.9
  - cf-units=2.1.1
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - cloudpickle=1.0.0
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.2.2
  - dask-core=1.2.2
  - distributed=1.28.0
  - expat=2.2.5
  - freetype=2.10.0
  - geos=3.7.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.8
  - iris=2.2.0
  - jinja2=2.10.1
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libcxx=8.0.0
#  - libcxxabi=8.0.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3
  - libiconv=1.15
  - liblapack=3.8.0
  - libmagic=5.36
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - libxslt=1.1.32
  - locket=0.2.0
  - lxml=4.3.3
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - msgpack-python=0.6.1
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - numpy=1.16.3
  - olefile=0.46
  - openblas=0.3.6
  - openssl=1.1.1b
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - partd=0.3.9
  - pika=1.0.1
  - pillow=6.0.0
  - pip=19.1
  - proj4=5.2.0
  - psutil=5.6.2
  - pycparser=2.19
  - pyepsg=0.4.0
  - pyhdf=0.10.1
  - pykdtree=1.3.1
  - pyke=1.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyshp=2.1.0
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-magic=0.4.15
  - pytz=2019.1
  - pyyaml=5.1
  - readline=7.0
  - requests=2.21.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - shapely=1.6.4
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - tblib=1.3.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.2
  - tqdm=4.31.1
  - udunits2=2.2.27.6
  - wheel=0.33.1
  - xarray=0.12.1
  - xmltodict=0.12.0
  - xz=5.2.4
  - yaml=0.1.7
  - zict=0.1.4
  - zlib=1.2.11
  - pip:
    - git+https://github.com/cedadev/ceda-elasticsearch-tools
    - git+https://github.com/cedadev/ceda-fbs
    - git+https://github.com/cedadev/nappy.git
    - docopt==0.6.2
    - elasticsearch==7.9.1
    - urllib3==1.24.3

